### ISSUE TITLE
Does this work with Kibana 5? 

### ISSUE THREAD

**Issue by wirecutter313** [bitsensor/elastalert-kibana-plugin#2]
I know they changed the install package in Kibana 5. I tried installing in my install and got an error of. 

/usr/share/kibana# ./bin/kibana-plugin install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip

Attempting to transfer from https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip

Transferring 8607971 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

Any thoughts?

**Comment by RubieV** [comment]
Untested in kibana 5, but it is easy to use the kibana 5 build process.
Just run `npm build`, and set file://`pwd`/build/archive.zip as -u
parameter.

As you can see in our ci, it's patched locally to produce kibana 4.x
compatible builds.

Let me know if it works, so that I can add kibana 5 support.

Op vr 17 feb. 2017 04:44 schreef wirecutter313 <notifications@github.com>:

**Comment by sudhirkumar1980** [comment]
Hi All,

I am getting following error while opening elastalert in kibana 5.3.

Fatal Error

Uncaught ReferenceError: require is not defined (http://XX.XXX.XX.XXX:5601/bundles/elastalert.bundle.js?v=14823:12)
Version: 5.3.0
Build: 14823
Error: Uncaught ReferenceError: require is not defined (http://XX.XXX.XX.XXX:5601/bundles/elastalert.bundle.js?v=14823:12)
    at window.onerror (http://XX.XXX.XX.XXX:5601/bundles/commons.bundle.js?v=14823:69:13503)

is there any workaround for it?

**Comment by SyCode7** [comment]
Hi, is there any update on this. I get errors when trying to install on Kibana 5.
