### ISSUE TITLE
ElastAlert Kibana plugin for 5.6.9

### ISSUE THREAD

**Issue by armenak** [bitsensor/elastalert-kibana-plugin#59]
Hello,

As far as I understand, this plugin works only with Kibana 5.6.8. Is there any way to make it work for Kibana 5.6.9?

Thanks,
Armenak

**Comment by armenak** [comment]
Ping

**Comment by martijnrondeel** [comment]
We're not publishing releases anymore for older Kibana versions, however, you can do the following to get the plugin to work with Kibana 5.6.9:

- Grab the 5.6.8 release [here](https://github.com/bitsensor/elastalert-kibana-plugin/tree/5.6.8).
- Open the archive.
- Edit the package.json file and change the version in: ```"kibana": {
    "version": "5.6.8"
  }``` to `5.6.9`.
- Zip the files back together and install the plugin as normal.

This will stop Kibana from not loading the plugin because of non-matching versions.
