### ISSUE TITLE
Plugin in Kibana 5.2.2 gets blank window

### ISSUE THREAD

**Issue by joaoantoniopereira** [bitsensor/elastalert-kibana-plugin#7]
Hi,
I am running elastalert kibana plugin in kibana 5.2.2.
I did:
./bin/kibana plugin -i elastalert -u https://git.bitsensor.io/front-end/elastalert-kibana-plugin/builds/5251/artifacts/file/build/elastalert-0.0.6.zip

Append to the config/kibana.yml file "elastalert.serverHost: localhost"

and
npm run build

When I open elastalert tab in kibana i get a blank window What am I doing wrong? Thanks!

![untitled2](https://cloud.githubusercontent.com/assets/24225656/24917663/c51d4ab4-1ed5-11e7-87a1-6b3e78022640.png)

**Comment by tatdatpham** [comment]
I got same error, and i see error log : 
`{"statusCode":502,"error":"Bad Gateway","message":"connect ECONNREFUSED 127.0.0.1:3030"}`

Server not start ?

**Comment by chinnareddy578** [comment]
Hey I'm encountering with same issues on above...

is it addressed anywhere..?

**Comment by johnflux** [comment]
(I'm a noob who got the same problem)

If I go to:

http://localhost:5601/api/elastalert/rules

I see:

"connect ECONNREFUSED 127.0.0.1:3030"

Port 3030 is the ElastAlert demon.  So basically the blank window is because it can't find ElastAlert.  (The demon itself from https://github.com/Yelp/elastalert not the plugin)

If you are running ElastAlert, then check its output for errors.

In my case, I'm was getting:

RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on')

I went to:  http://localhost:5601/app/kibana#/dev_tools/console?_g=()

And then typed in:   DELETE /elastalert_status

and ran that.  Then in the elastalert folder, run:  python elastalert/create_index.py

Then rerun: python elastalert/elastalert.py --verbose

I haven't gotten further than this though.
