### ISSUE TITLE
ECONNREFUSED 127.0.0.1:3030

### ISSUE THREAD

**Issue by uranru** [bitsensor/elastalert-kibana-plugin#74]
Hello
I have an error:
502 - Bad Gateway
connect ECONNREFUSED 127.0.0.1:3030

What should I do?
I see the team netstat
port 3030 is not used.
How to run Elastalert server?

**Comment by martijnrondeel** [comment]
This is (most-likely) related to not having a running ElastAlert server. Please read the instructions on how to run ElastAlert server [here](https://github.com/bitsensor/elastalert#installation).

**Comment by shirakaba** [comment]
@uranru I just experienced this.

# Kibana config

In my case, the ElastAlert server was running, but Kibana's configuration for connecting to it was incorrect. Ensure that your `kibana.yml` file includes the following config:

```YAML
elastalert-kibana-plugin.serverHost: "127.0.0.1"
elastalert-kibana-plugin.serverPort: 3030
```

# Verifying Kibana -> ElastAlert reachability

If Kibana is running inside a Docker container, you can verify whether it has access to ElastAlert by running the following command:

```sh
# Where '968cc14c4777' is the container id for Kibana 
docker exec -it 968cc14c4777 curl http://127.0.0.1:3030

# Response if reachable:
#   {"name":"elastalert-server","port":3030,"version":"0.0.14"}

# Response if not reachable:
#   curl: (7) Failed connect to 127.0.0.1:3030; Connection refused
```

Once you identify an endpoint that connects, modify the `elastalert-kibana-plugin.serverHost` and `elastalert-kibana-plugin.serverPort` values (specified above) accordingly.

# If using Docker 'bridge' networking

In my case, I was using Docker 'bridge' networking rather than 'host' networking, so the `127.0.0.1` interface of each container was isolated to each container, not mutually visible amongst all of them.

In my docker-compose script, I'd specified the service name for ElastAlert as "elastalert", so I tried connecting to `http://elastalert:3030` from the Kibana container as above, and it worked.

Thus, this Kibana config worked in my case:

```YAML
elastalert-kibana-plugin.serverHost: "elastalert"
elastalert-kibana-plugin.serverPort: 3030
```

Whether this applies to your setup, I can't say!
