### ISSUE TITLE
Problem with Elastalert-Kibana-Plugin for elasticsearch 6.3.2

### ISSUE THREAD

**Issue by hamzaouadia** [bitsensor/elastalert-kibana-plugin#77]
I got elastalert up and running but the kibana plugin keeps giving me this error
![image](https://user-images.githubusercontent.com/18106793/48668305-e4162d80-eae1-11e8-9798-e2f53fe3dd03.png)

I installed elastalert following the documentation but the plugin still don't work for me
Can i get some insight ? thank you

**Comment by rlkarren** [comment]
Configuration

By default the plugin will connect to localhost:3030. **If your ElastAlert server is running on a different host or port add/change the following options in your config/kibana.yml file:**

elastalert-kibana-plugin.serverHost: 123.0.0.1
elastalert-kibana-plugin.serverPort: 9000

**Comment by Subash-Chandra** [comment]
So i'm having the same issue. @martijnrondeel @rlkarren 

My Elastalert is running on port 3030(docker-compose says `port: - 3030:3030`)

I've put in the following 2 lines as instructed to do in the documentation for the plugin because running it by default still gave me the 502 - ECONNREFUSED error
`elastalert-kibana-plugin.serverHost: 123.0.0.1`
`elastalert-kibana-plugin.serverPort: 3030`

My Elastalert container throws no errors.

I presume the error is because my host is not localhost or `123.0.0.1`. How would i go about confirming what the host is?

**Comment by rlkarren** [comment]
elastalert-kibana-plugin.serverHost: <IP address of your kibana host>
elastalert-kibana-plugin.serverPort: <Port used by your Kibana host>

the **elastalert-kibana-plugin.serverPort:**  config item is not needed if your Kibana host is using the default port of 5601 and can be commented out or not used at all.
