### ISSUE TITLE
Version for 6.5

### ISSUE THREAD

**Issue by DpoBoceka** [bitsensor/elastalert-kibana-plugin#78]
Just found the plugin but we've already moved out stack to 6.5 release. Is there any chance that the plugin would be available for it?

**Comment by martijnrondeel** [comment]
I've added a release for 6.5.0 [here](https://github.com/bitsensor/elastalert-kibana-plugin/releases/tag/1.0.1).

**Comment by centralscrutiniser** [comment]
Hiya, 

Kibana on the latest here, but the 6.5 version doesn't install - 

`root@kibana00:/usr/share/kibana# bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-6.5.0.zip
Attempting to transfer from https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-6.5.0.zip
Transferring 20147045 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [elastalert-kibana-plugin]. Expected [6.5.1]; found [6.5.0]"
root@kibana00:/usr/share/kibana# apt-get update
Hit:1 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:3 http://gb.archive.ubuntu.com/ubuntu xenial InRelease                                                         
Get:4 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                        
Get:5 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                 
Ign:6 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Hit:7 https://artifacts.elastic.co/packages/6.x/apt stable Release
Fetched 323 kB in 0s (380 kB/s)
Reading package lists... Done
root@kibana00:/usr/share/kibana# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.`

Andy
